global_frame: map
rolling_window: true
track_unknown_space: false

width: 200
height: 200

plugins:
  - {name: obstacle_layer,            type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,           type: "costmap_2d::InflationLayer"}