global_frame: odom
rolling_window: true
track_unknown_space: false

width: 100
height: 100

plugins:
  - {name: obstacle_layer,            type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,           type: "costmap_2d::InflationLayer"}