nb_of_topics: 1
rate: 10
topic_1:
  name: heartbeat
  topic_name: /heartbeat
  min_freq: 1
  use_average: false
  monitoring_rate: 0.5

# topic_2:
#   name: imu
#   topic_name: /imu/data
#   min_freq: 40
#   use_average: false
#   monitoring_rate: 10

# topic_3:
#   name: depth_camera
#   topic_name: /d435/depth/color/points
#   min_freq: 3
#   use_average: false
#   monitoring_rate: 10

# topic_4:
#   name: gps
#   topic_name: /fix
#   min_freq: 0.5
#   use_average: false
#   monitoring_rate: 10

# topic_5:
#   name: base_odom
#   topic_name: /base_odom
#   min_freq: 5
#   use_average: true
#   monitoring_rate: 5